//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jctravel01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country01()
        {
            this.AirlineOffice = new HashSet<AirlineOffice>();
            this.AirportInfo = new HashSet<AirportInfo>();
            this.City03 = new HashSet<City03>();
            this.Hotel = new HashSet<Hotel>();
            this.Restaurant = new HashSet<Restaurant>();
            this.Scenery = new HashSet<Scenery>();
            this.State02 = new HashSet<State02>();
            this.TourBure = new HashSet<TourBure>();
        }
    
        public int CountryIndex { get; set; }
        public string Country_no { get; set; }
        public string ShortName { get; set; }
        public int PDivisionIndex { get; set; }
        public string Cname { get; set; }
        public string Ename { get; set; }
        public string Continent { get; set; }
        public string Tele_CountryCode { get; set; }
        public Nullable<int> Tele_DialCode { get; set; }
        public string Voltage { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Plugcode { get; set; }
        public string Currency_code { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<int> Status { get; set; }
        public int Order { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateBy_Time { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateBy_Time { get; set; }
        public string CompanyNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirlineOffice> AirlineOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirportInfo> AirportInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City03> City03 { get; set; }
        public virtual UpDivision UpDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Restaurant> Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenery> Scenery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State02> State02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourBure> TourBure { get; set; }
    }
}
