//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jctravel01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Hotel_Theme = new HashSet<Hotel_Theme>();
            this.Hotel_Type = new HashSet<Hotel_Type>();
            this.HotelFacility = new HashSet<HotelFacility>();
            this.HotelOutLook = new HashSet<HotelOutLook>();
            this.HotelService = new HashSet<HotelService>();
            this.Img = new HashSet<Img>();
            this.NearbyFacility = new HashSet<NearbyFacility>();
            this.RoomFacility = new HashSet<RoomFacility>();
            this.RoomType = new HashSet<RoomType>();
        }
    
        public int HotelIndex { get; set; }
        public int CountryIndex { get; set; }
        public int CityIndex { get; set; }
        public string Holtel_no { get; set; }
        public string ShortName { get; set; }
        public string Ename { get; set; }
        public string Cname { get; set; }
        public Nullable<int> CityDistrictIndex { get; set; }
        public string Tele_CountryCode { get; set; }
        public string Tele_Area { get; set; }
        public string Tele1 { get; set; }
        public string tele2 { get; set; }
        public string Contact1 { get; set; }
        public string Contact1_Tele { get; set; }
        public string Contact2 { get; set; }
        public string Contact2_tele { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string Blog { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Addr { get; set; }
        public string Introduction { get; set; }
        public string Locate_des { get; set; }
        public Nullable<double> Star { get; set; }
        public Nullable<System.TimeSpan> Checkin { get; set; }
        public Nullable<System.TimeSpan> Checkout { get; set; }
        public Nullable<int> BuildingNo { get; set; }
        public Nullable<int> TopNo { get; set; }
        public Nullable<int> TotalRoom { get; set; }
        public int Status { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateBy_Time { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateBy_Time { get; set; }
        public string CompanyNo { get; set; }
    
        public virtual City03 City03 { get; set; }
        public virtual CityDistrict CityDistrict { get; set; }
        public virtual Country01 Country01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_Theme> Hotel_Theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_Type> Hotel_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelFacility> HotelFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelOutLook> HotelOutLook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelService> HotelService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Img> Img { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NearbyFacility> NearbyFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomFacility> RoomFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomType> RoomType { get; set; }
    }
}
