//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jctravel01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRInfo()
        {
            this.PasMng = new HashSet<PasMng>();
            this.PermiMng = new HashSet<PermiMng>();
        }
    
        public int EmpIndex { get; set; }
        public string EmpNo { get; set; }
        public string CompanyNo { get; set; }
        public int Dep_Index { get; set; }
        public int JobLevel_Index { get; set; }
        public int JobGruop_Index { get; set; }
        public string EmpEnName { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> JobManager { get; set; }
        public string JobTitle { get; set; }
        public string EmpID { get; set; }
        public System.DateTime EmpBday { get; set; }
        public string ComPhone { get; set; }
        public string ComExt { get; set; }
        public string ComEmail { get; set; }
        public string HomeAddres { get; set; }
        public string ContactAddres { get; set; }
        public string PrivateMail { get; set; }
        public string PrivatePhone { get; set; }
        public string UrgentName { get; set; }
        public string RelationUrgent { get; set; }
        public string UrgentPhone { get; set; }
        public int OnJobStatus { get; set; }
        public System.DateTime OnBoardDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateBy_Time { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateBy_Time { get; set; }
        public bool AllowLogIn { get; set; }
    
        public virtual CoIndex CoIndex { get; set; }
        public virtual DepIndex DepIndex { get; set; }
        public virtual JobGruopIndex JobGruopIndex { get; set; }
        public virtual JobLevelIndex JobLevelIndex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasMng> PasMng { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermiMng> PermiMng { get; set; }
    }
}
