//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jctravel01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Img
    {
        public long ImgIndex { get; set; }
        public string CompanyNo { get; set; }
        public int POI_Type { get; set; }
        public Nullable<int> Scenery_index { get; set; }
        public Nullable<int> RestIndex { get; set; }
        public Nullable<int> HotelIndex { get; set; }
        public int OrderNo { get; set; }
        public string ImgPath { get; set; }
        public string ImgInfo { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateBy_Time { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateBy_Time { get; set; }
        public int Status { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual Scenery Scenery { get; set; }
    }
}
