//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jctravel01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logInLog
    {
        public System.Guid LogInIndex { get; set; }
        public string CompanyNo { get; set; }
        public int EmpIndex { get; set; }
        public string LogInPlace { get; set; }
        public System.DateTime LogInTime { get; set; }
        public string LogInPsd { get; set; }
        public bool ErrorLog { get; set; }
        public bool ErrorLogInLog { get; set; }
        public bool AllowLogIn { get; set; }
        public string LoginIp { get; set; }
    }
}
