//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jctravel01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Img = new HashSet<Img>();
            this.Res_Theme = new HashSet<Res_Theme>();
            this.Res_Type = new HashSet<Res_Type>();
            this.ResAmos = new HashSet<ResAmos>();
            this.ResDining = new HashSet<ResDining>();
        }
    
        public int RestIndex { get; set; }
        public string Rest_no { get; set; }
        public int CountryIndex { get; set; }
        public int CityIndex { get; set; }
        public string ShortName { get; set; }
        public string Ename { get; set; }
        public string Cname { get; set; }
        public Nullable<int> CityDistrictIndex { get; set; }
        public string Tele_CountryCode { get; set; }
        public string Tele_Area { get; set; }
        public string Tele1 { get; set; }
        public string Tele2 { get; set; }
        public string Contact1 { get; set; }
        public string Contact1_tele { get; set; }
        public string Contact2 { get; set; }
        public string Contact2_tele { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string Blog { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Cuisine { get; set; }
        public Nullable<System.TimeSpan> Open_Time { get; set; }
        public Nullable<System.TimeSpan> Close_Time { get; set; }
        public Nullable<bool> ForNight { get; set; }
        public Nullable<int> TimeLimit { get; set; }
        public string Addr { get; set; }
        public string Introduction { get; set; }
        public string Locate_des { get; set; }
        public string Cuisine_Set { get; set; }
        public string Menu { get; set; }
        public string Dayoff { get; set; }
        public int Status { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateBy_Time { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateBy_Time { get; set; }
        public string CompanyNo { get; set; }
    
        public virtual City03 City03 { get; set; }
        public virtual CityDistrict CityDistrict { get; set; }
        public virtual Country01 Country01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Img> Img { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Res_Theme> Res_Theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Res_Type> Res_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResAmos> ResAmos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResDining> ResDining { get; set; }
    }
}
