//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jctravel01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scenery()
        {
            this.Img = new HashSet<Img>();
            this.Scenery_Theme = new HashSet<Scenery_Theme>();
            this.Scenery_Type = new HashSet<Scenery_Type>();
        }
    
        public int Scenery_index { get; set; }
        public int CountryIndex { get; set; }
        public int CityIndex { get; set; }
        public string Scenery_no { get; set; }
        public string ShortName { get; set; }
        public string Ename { get; set; }
        public string Cname { get; set; }
        public Nullable<int> CityDistrictIndex { get; set; }
        public string Tele_CountryCode { get; set; }
        public string Tele_Area { get; set; }
        public string Tele_number { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string Blog { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Addr { get; set; }
        public string Introduction { get; set; }
        public string Fee { get; set; }
        public string Locate_des { get; set; }
        public Nullable<int> Found_Date { get; set; }
        public Nullable<int> Stay_Time { get; set; }
        public Nullable<int> Bulit_Area { get; set; }
        public string Suggestion { get; set; }
        public Nullable<System.TimeSpan> Start_time { get; set; }
        public Nullable<System.TimeSpan> LastCall { get; set; }
        public Nullable<System.TimeSpan> Close_time { get; set; }
        public string TimeSheet { get; set; }
        public string Dayoff { get; set; }
        public Nullable<bool> ForNight { get; set; }
        public Nullable<int> SafeLevel { get; set; }
        public Nullable<bool> MainPoint { get; set; }
        public int Status { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateBy_Time { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateBy_Time { get; set; }
        public string CompanyNo { get; set; }
    
        public virtual City03 City03 { get; set; }
        public virtual CityDistrict CityDistrict { get; set; }
        public virtual Country01 Country01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Img> Img { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenery_Theme> Scenery_Theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenery_Type> Scenery_Type { get; set; }
    }
}
